version: '3.8'

services:
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: '--server-id=1 --log-bin=mysql-bin --log-slave-updates=1 --gtid-mode=ON --enforce-gtid-consistency=1'
    volumes:
      - ./master.cnf:/etc/my.cnf

  mysql-replica1:
    image: mysql:latest
    container_name: mysql-replica1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_MASTER_HOST: mysql-master
      MYSQL_MASTER_PORT: 3306
      MYSQL_MASTER_ROOT_PASSWORD: root
    depends_on:
      - mysql-master
    ports:
      - "3307:3306"
    command: '--server-id=2 --log-bin=mysql-bin --log-slave-updates=1 --gtid-mode=ON --enforce-gtid-consistency=1 --skip-networking=0 --skip-slave-start=1'
    volumes:
      - ./replica.cnf:/etc/my.cnf


  mysql-replica2:
    image: mysql:latest
    container_name: mysql-replica2
    depends_on:
      - mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_MASTER_HOST: mysql-master
      MYSQL_MASTER_PORT: 3306
      MYSQL_MASTER_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    command: '--server-id=3 --log-bin=mysql-bin --log-slave-updates=1 --gtid-mode=ON --enforce-gtid-consistency=1 --skip-networking=0 --skip-slave-start=1'
    volumes:
      - ./replica.cnf:/etc/my.cnf
